#+STARTUP: logdone
* Machine Learning 					    :MachineLearning:


** Links of interest

- Great online tutorials here http://ufldl.stanford.edu/tutorial/
- http://www.deeplearningbook.org :: A full online book on deep learning with background material
- GPU accelerated machine learning: http://www.nvidia.com/object/machine-learning.html
- Caffe: http://caffe.berkeleyvision.org/
- Theano: http://deeplearning.net/software/theano/
- Torch: http://torch.ch/
- DIGITS: https://developer.nvidia.com/digits
- cuDNN: https://developer.nvidia.com/cudnn

*** Notes from http://www.deeplearningbook.org		 :AI:MachineLearning:

**** Chapter 6
Feedforward neural networks are also called multilayer perceptrons and are 
the basis of neural networks. There is no "feedback" in these models. The goal
of FFNN is to map $y \approx f(x; \theta)$. Then, the job of the FFNN training 
is to learn $\theta$.

In order to map x to the input layer, we can define a function $\phi$ that 
provides a *new* set of features that represent x. The question is, then,
how to choose $\phi$. Doing this by hand, with lots of human intervention
based on expert knowledge and understanding of the systems involved, used
to be the dominant approach. *The novelty of Deep Learning is to learn $\phi$*. 
The strategy of deep learning is to learn \phi. In this approach, we have 
a model $y = f(x;θ, w) = \phi(x; \theta)^{T}w$. We now have parameters
\theta that we use to learn \phi from a broad class of functions, 
and parameters w that map from $\phi(x)$ to the desired output. This 
is an example of a deep feedforward network, with \phi deﬁning a hidden layer. 

**** TODO Chapter 7 [33%]
  - [X] stuff
  - [ ] stuff2
  - [ ] Stuff3


* Emacs Notes

- M-x xterm-mouse-mode to allow mouse clicking to control things
- 

* Meeting notes

** DONE Meeting with Anastasia in Warren's office
   SCHEDULED: <2016-05-12 Thu 10:00-10:45>

- Warren brings up clinical trials searching
  - Need structured eligibility data
  - Need structured data in general 
  - Incorporate controlled vocabularies into clinical trials

- Carl's branch
  - A business app side of things
  - A vision/strategy side

- Jeff's branch
We own two things:
  - Network
  - Security
Everything else is shared.

** Meeting with Anastasia
<2016-05-18 Wed 14:00-15:00>
*** TODO Introduce Anastasia to Phil Bourne
    DEADLINE: <2016-05-20 Fri>
*** TODO Introduce Anastasis to Andrea Norris
    DEADLINE: <2016-05-20 Fri>
*** TODO Send Anastasia Informatics Documents
    DEADLINE: <2016-05-20 Fri>

*** TODO Set up regular meeting with Anastasia
*** TODO Invite Anastasia to Data Science Lunch
Mainly discussed NIH/NCI organizational structure



* Meetings and Travel

** TODO UPenn/CHOP inaugural Mid-Atlantic Bioinformatics Conference 
<2016-10-26 Wed>

*** TODO Travel for UPenn/CHOP meeting [0%]
    DEADLINE: <2016-05-20 Fri>
- [ ] get formal invitation
- [ ] schedule travel with Nancy

#+BEGIN_QUOTE
Dear Dr. Davis:

We would like to invite you to be a speaker at the UPenn/CHOP inaugural Mid-Atlantic Bioinformatics Conference on October 26, 2016, to be held on the research campus of the Children’s Hospital of Philadelphia, adjacent to the University of Pennsylvania.

The topic of the conference is Computational Challenges for Precision Medicine. 

We have some great speakers who have already accepted: Scott Zeger from JHU, Josh Stuart from UCSC, Paul  Boutros from OICR, Dana Crawford from Case Western, Jeff Hammerbacher from Mt. Sinai, and from UPenn/CHOP are Kai Tan, Sharon Diskin and Robert Faryabi.

The committee who selected you as an invited speaker include the following UPenn and CHOP faculty:

Hongzhe Li 
Yoseph Barash
Li-San Wang
Kai Tan
Sharon Diskin
Blanca Himes
Deanne Taylor
Mingyao Li
Robert Faryabi

We will pay for travel, hotel, meals,  and offer an honorarium of $500. You are also invited to a dinner to be held the night previous (10/25) for all our speakers to meet one another.  Also, if there are additional faculty or people you’d like to visit at the University of Pennsylvania or at CHOP the day before on 10/25 we would be happy to set up meetings for you that day.

Thank you!

Deanne
#+END_QUOTE
