#+STARTUP: logdone
* IT projects

* Admin projects
** Genomic Data Sharing project
*** Meeting about GDS tracking site
    SCHEDULED: <2016-05-16 Mon 13:00-14:00>



* Science projects

** Myriem20160513
   :PROPERTIES:
   :Project:   Myriem20160513
   :PI:        Kebebew
   :Requested: 2016-05-10
   :END:
Myriem Boufraqech mailto:myriem.boufraqech@nih.gov asked to look at three sets
of variant calls representing:
- Tumor
- Tumor-derived Cell Line
- Blood

She is interested in whether the cell line represents tumor and wants to
use the prepared calls (available as single excel files per sample, Ion 
Torrent) to prove that the tumor and cell line are the same. I talked with
her about the likelihood that we would not be able to determine that
relationship from the limited data.

*** DONE Myriem's analysis [100%]
    CLOSED: [2016-05-13 Fri 11:02] SCHEDULED: <2016-05-13 Fri>
  - [X] Calculate overlap among variant calls
  - [X] Generate Venn diagram

*** DONE deliver results to Myriem
    CLOSED: [2016-05-13 Fri 06:39] SCHEDULED: <2016-05-13 Fri>

*** TODO Need more details for Myriem
    SCHEDULED: <2016-05-17 Tue>
Myriem is looking for more details in the analysis. In particular, I think
she wants a list of variants that are shared by the tumor and cell line but
not in the blood.




* Old Projects
** ShinySRAdb
*** TODO Clean up app a bit
*** TODO Consider publishing on F1000R or at least bioRxiv

