#+COLUMNS: %25ITEM(Task) %5TODO(To-do) %1PRIORITY %10TAGS %PI %Project
#+STARTUP: logdone
* IT projects

* Admin projects
** Genomic Data Sharing project
*** Meeting about GDS tracking site
<2016-05-16 Mon 13:00-14:00>



* Science projects

** Myriem20160513
   :PROPERTIES:
   :Project:   Myriem20160513
   :PI:        Kebebew
   :Requested: 2016-05-10
   :END:
Myriem Boufraqech mailto:myriem.boufraqech@nih.gov asked to look at three sets
of variant calls representing:
- Tumor
- Tumor-derived Cell Line
- Blood

She is interested in whether the cell line represents tumor and wants to
use the prepared calls (available as single excel files per sample, Ion 
Torrent) to prove that the tumor and cell line are the same. I talked with
her about the likelihood that we would not be able to determine that
relationship from the limited data.

*** DONE Myriem's analysis [100%]
    CLOSED: [2016-05-13 Fri 11:02] SCHEDULED: <2016-05-13 Fri>
  - [X] Calculate overlap among variant calls
  - [X] Generate Venn diagram

*** DONE deliver results to Myriem
    CLOSED: [2016-05-13 Fri 06:39] SCHEDULED: <2016-05-13 Fri>

*** DONE Need more details for Myriem
    CLOSED: [2016-05-17 Tue 18:21] DEADLINE: <2016-05-17 Tue>
Myriem is looking for more details in the analysis. In particular, I think
she wants a list of variants that are shared by the tumor and cell line but
not in the blood.



** TARGET Osteosarcoma
   :PROPERTIES:
   :Project:   TARGET Osteo
   :PI:        Meltzer
   :Requested: 2013-01-01
   :END:

*** Meetings
**** TARGET Osteosarcoma Conference call
     <2016-05-19 Thu 14:00-15:00>
Discussion is with St. Jude about bad samples.  
- 25 "bad" samples
  - Mixture of bad libraries and sample mismatch.
- Pipeline that St. Jude is using
  - Structural variation
    - CREST
  - Small somatic variants
    - "internal pipeline"--St. Jude not willing to share at this time, despite lots of asking
  - LOH
    - 10x coverage in dbSNP

* Old Projects							    :ARCHIVE:
** ShinySRAdb
*** TODO Clean up app a bit
*** TODO Consider publishing on F1000R or at least bioRxiv

