# Use this to test the setup
apiVersion: v1
kind: Pod
metadata:
  name: workload-identity-test-2
  namespace: default
spec:
  containers:
  - image: google/cloud-sdk:slim
    name: workload-identity-test
    command: ["sleep","infinity"]
  serviceAccountName: gcp-workload-identity
# Not needed on autopilot
#  nodeSelector:
#    iam.gke.io/gke-metadata-server-enabled: "true"
